# Generated by Django 2.2.9 on 2020-07-30 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20200730_1843'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Temp1',
        ),
        migrations.AlterModelOptions(
            name='group',
            options={},
        ),
    ]
